---
output: html_document
editor_options: 
  chunk_output_type: console
---
---
title: "Stock Strategy Exploration and Automation"
author: 
- Abram Yorde
- Karen Richard
- Paul Fullenkamp
date: "October 1, 2018"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_depth: 1
    toc_float: true
---

```{r setup, include=FALSE}
devtools::install_github("Emerson-Data-Science/EmersonDataScience",  
                         auth_token = "7c54299b0c824b305a01dc1eeb9a6de41fe12b23",  
                         INSTALL_opts = '--no-multiarch',  
                         dependencies = TRUE,  
                         quiet = FALSE,  
                         upgrade = FALSE)
library(EmersonDataScience)

##########################################################################
Required_Packages = c('tidyverse','installr','psych','quantmod','lubridate','dygraphs','doParallel','XML','earth', 'googledrive','cumstats','dummy','plotly','knitr','xts')
load_or_install(Required_Packages)

## Checking for R updates
updateR(fast = F,
        browse_news = F,
        install_R = T,
        copy_packages = F,
        copy_Rprofile.site = T,
        keep_old_packages = F,
        update_packages = F,
        start_new_R = F,
        quit_R = T,
        print_R_versions = T,
        GUI = F,
        to_checkMD5sums = T,
        keep_install_file = F)

## Loading Required Functions
sourceDir(paste0(getwd(),'/Codes/Functions/'))

## Root Data Folder
Root_Folder = getwd()

## Disabling API Warning
options("getSymbols.yahoo.warning" = FALSE)
options("getSymbols.warning4.0" = FALSE)

## General RMD Options
Local_S = T
Local_L = T
Google_Drive_S = F
Google_Drive_L = F
Initial_Pull = F
TEST = T

## Google Drive Maintinance
if(Google_Drive_L | Google_Drive_S){
  drive_empty_trash()
}
```

```{r Initial Data Pull, include = F, eval = !TEST}
if(Initial_Pull){
  
  NASDAQ_Stocks = read.csv(paste0(Root_Folder,"/Data/NASDAQ.csv"))
  AMEX_Stocks = read.csv(paste0(Root_Folder,"/Data/AMEX.csv"))
  NYSE_Stocks = read.csv(paste0(Root_Folder,"/Data/NYSE.csv"))
  Market_Tickers = data.frame(Symbol = c("^GSPC","^IXIC","^DJI"),
                              Name = c("S&P 500","NASDAQ","Dow Jones"),
                              IPOyear = as.character(year(Sys.Date()) - 5),
                              LastSale = "1000")
  
  Total_Stocks = bind_rows(Market_Tickers,NASDAQ_Stocks,NYSE_Stocks,AMEX_Stocks) %>%
    mutate(IPOyear = as.numeric(as.character(IPOyear)),
           LastSale = as.numeric(as.character(LastSale))) %>%
    filter(!is.na(IPOyear),
           !is.na(LastSale)) %>%
    filter(IPOyear <= year(Sys.Date()) - 5,
           IPOyear >= year(Sys.Date()) - 15,
           LastSale >= 10)
  Dump = list()
  
  p = progress_estimated(n = nrow(Total_Stocks),min_time = 3)
  for(i in 1:nrow(Total_Stocks)){
    p$pause(0.1)$tick()$print()
    ticker = as.character(Total_Stocks$Symbol[i])
    
    
    stockData = try(getSymbols(
      ticker,
      src = "yahoo",
      auto.assign = FALSE) %>%
        as.data.frame() %>%
        mutate(Date = ymd(rownames(.))))
    if("try-error" %in% class(stockData)){
      Dump[[i]] = stockData
    }else{
      colnames(stockData) = c("Open","High","Low","Close","Volume","Adjusted","Date")
      stockData$Stock = ticker
      Dump[[i]] = stockData
    }
  }
  list.condition <- sapply(Dump, function(x) class(x) == "data.frame")
  output.list  <- Dump[list.condition]
  Combined_Results = plyr::ldply(output.list,data.frame)
  
  Combined_Results = Combined_Results %>%
    group_by(Stock) %>%
    na.locf() %>%
    ungroup()
  
  
  if(Local_S){
    save(Combined_Results,
         file = paste0(Root_Folder,"/Data//NASDAQ Historical.RDATA"))
  }
  if(Google_Drive_S){
    save(Combined_Results,
         file = paste0(tempdir(),'/',"NASDAQ Historical.RDATA"))
    Check = drive_find("NASDAQ Historical.RDATA")
    if(nrow(Check) > 0){
      drive_rm("NASDAQ Historical.RDATA")
    }
    drive_upload(media =paste0(tempdir(),'/',"NASDAQ Historical.RDATA"),
                   path = "NASDAQ Historical.RDATA")
  }
}

```

```{r Data Update, include = F,eval = !TEST}
# Takes About 15 Minutes

if(!Initial_Pull){
  if(Local_L){
    Ticker_Pull_Function(Location = paste0(Root_Folder,"/Data/"),Google_Drive = F)
  }
  if(Google_Drive_L){
    Ticker_Pull_Function(Google_Drive = T)
  }
}
```

```{r Market Designation, include = F, eval = !TEST}
if(Google_Drive_L){
  File = drive_download(file = "NASDAQ Historical.RDATA",
                        overwrite = T)
  load(File$local_path)
  rm(File)
}
if(Local_L){
  load(paste0(Root_Folder,"/Data/NASDAQ Historical.RDATA"))
}


## Defining Market Directions
Market_DF = Combined_Results %>%
  filter(Stock %in% c("^GSPC","^IXIC","^DJI")) %>%
  group_by(Stock) %>%
 mutate(Indicator = runMax(Adjusted,90),
        Delta = (Adjusted -Indicator)/Indicator) %>%
  na.omit() %>%
  mutate(Market_Status = as.factor(case_when(
    Delta <= -0.20 ~ "Bear",
    Delta <= -0.10 ~ "Correction",
    Delta < -0.05 ~ "Pullback",
    Delta >= -0.05 ~ "Bull"
  ))) %>%
  ungroup()

Plot_DF = Market_DF
Plot_DF[Plot_DF$Stock == "^GSPC","Stock"] = "S&P 500"
Plot_DF[Plot_DF$Stock == "^IXIC","Stock"] = "NASDAQ"
Plot_DF[Plot_DF$Stock == "^DJI","Stock"] = "Dow Jones"
Plot_DF$Market_Status = factor(Plot_DF$Market_Status, levels = c("Bull",
                                                                 "Pullback",
                                                                 "Correction",
                                                                 "Bear"))



## Final_Indicator
Market_Ind = Market_DF %>%
  select(Date,Stock,Market_Status) %>%
  spread(key = Stock, value = Market_Status) %>%
  mutate(Market_Status = case_when(
    `^GSPC` == "Bear" | `^IXIC` == "Bear" | `^DJI` == "Bear" ~ "Bear",
    `^GSPC` == "Correction" | `^IXIC` == "Correction" | `^DJI` == "Correction" ~ "Correction",
    `^GSPC` == "Pullback" | `^IXIC` == "Pullback" | `^DJI` == "Pullback" ~ "Pullback",
    TRUE ~ "Bull"
  )) %>%
  select(Date,Market_Status)
glimpse(arrange(Market_Ind,desc(Date)))

if(Local_S){
save(Market_Ind,Plot_DF,
     file = paste0(Root_Folder,"/Data//Market_Ind.RDATA"))
}
if(Google_Drive_S){
    save(Market_Ind,Plot_DF,
         file = paste0(tempdir(),'/',"Market_Ind.RDATA"))
    Check = drive_find("Market_Ind.RDATA")
    if(nrow(Check) > 0){
      drive_rm("Market_Ind.RDATA")
    }
    drive_upload(media =paste0(tempdir(),'/',"Market_Ind.RDATA"),
                   path = "Market_Ind.RDATA")
}
```


```{r Pool Reduction, include = F, eval = !TEST}
if(Google_Drive_L){
  File = drive_download(file = "NASDAQ Historical.RDATA",
                        overwrite = T)
  load(File$local_path)
  rm(File)
  File = drive_download(file = "Market_Ind.RDATA",
                        overwrite = T)
  load(File$local_path)
  rm(File)
}
if(Local_L){
  load(paste0(Root_Folder,"/Data/NASDAQ Historical.RDATA"))
  load(paste0(Root_Folder,"/Data//Market_Ind.RDATA"))
}

## Takes about 5 Minutes  
Start = Sys.time()
print("Initial Stat Calculation for Pool Selection")
PR_Stage = PR_Appendage(Combined_Results,parallel = T)
Sys.time() - Start
Major_Indexs = c("^GSPC","^IXIC","^DJI")
Index_Beta_Slope = PR_Stage %>%
  filter(Stock %in% Major_Indexs) %>%
  select(Stock,Date,Close_Slope_50_Norm) %>%
  spread(Stock,Close_Slope_50_Norm) %>%
  mutate(Beta_Slope = rowMeans(cbind(`^GSPC`,`^IXIC`,`^DJI`))) %>%
  select(Date,Beta_Slope)
PR_Stage_R2 = PR_Stage %>%
  left_join(Index_Beta_Slope,by = "Date") %>%
  na.omit() %>%
  mutate(Pseudo_Beta_PD = (Close_Slope_50_Norm - Beta_Slope)/Beta_Slope) %>%
  select(-Beta_Slope)


## Initial Pool Reduction
NASDAQ_Stocks = read.csv(paste0(Root_Folder,"/Data/NASDAQ.csv"))
AMEX_Stocks = read.csv(paste0(Root_Folder,"/Data/AMEX.csv"))
NYSE_Stocks = read.csv(paste0(Root_Folder,"/Data/NYSE.csv"))
Total_Stocks = bind_rows(NASDAQ_Stocks,AMEX_Stocks,NYSE_Stocks)

PR_Red_1 = PR_Stage_R2 %>%
  filter(Date == max(Date)) %>%
  group_by(Stock) %>%
  filter(n() == 1) %>%
  ungroup() %>%
  left_join(Total_Stocks,by = c("Stock" = "Symbol")) %>%
  select(-c(X,Summary.Quote,LastSale)) %>%
  na.omit() %>%
  mutate(Volume_PD_Norm_Rank = scales::rescale(Volume_PD_Norm,c(0,1)),
         Volume_SD_Norm_Rank = scales::rescale(Volume_SD_Norm,c(0,1)),
         Close_High_PD_Norm_Rank = scales::rescale(Close_High_PD_Norm,c(0,1)),
         Close_PD_50_Norm_Rank = scales::rescale(Close_PD_50_Norm,c(0,1)),
         Close_PD_200_Norm_Rank = scales::rescale(Close_PD_200_Norm,c(0,1)),
         Close_SD_50_Norm_Rank = scales::rescale(Close_SD_50_Norm,c(0,1)),
         Close_PD_50_200_Norm_Rank = scales::rescale(Close_PD_50_200_Norm,c(0,1)),
         Close_Slope_50_Norm_Rank = scales::rescale(Close_Slope_50_Norm,c(0,1)),
         Close_Slope_200_Norm_Rank = scales::rescale(Close_Slope_200_Norm,c(0,1)),
         Close_50_Time_Norm_Rank = scales::rescale(Close_50_Time_Norm,c(0,1)),
         Price_Range_15_SD_Norm_Rank = scales::rescale(Price_Range_15_SD_Norm,c(0,1)),
         Pseudo_Beta_PD_Rank = scales::rescale(Pseudo_Beta_PD,c(0,1)))
  
  

## Appending FinViz Stats
## Takes About 2 Minutes
Start = Sys.time()
storage = list()
print("Beginning Pool Selection FinViz Stat Pull")
p = progress_estimated(nrow(PR_Red_1))
for(i in 1:nrow(PR_Red_1)){
  Ticker = PR_Red_1$Stock[i]
  TMP = try(FinViz_Metric_Pull(Ticker),
            silent = T)
  storage[[i]] = TMP
  p$pause(0.5)$tick()$print()
}
Metrics = plyr::ldply(storage[sapply(storage,class) %in% "data.frame"],data.frame)
Sys.time() - Start

Pool_Results = PR_Red_1 %>%
  left_join(Metrics,by = "Stock") %>%
  mutate(Profit.Margin = as.numeric(str_remove(Profit.Margin,"%"))/100,
         Oper..Margin = as.numeric(str_remove(Oper..Margin,"%"))/100,
         Change = as.numeric(str_remove(Change,"%"))/100,
         Price = as.numeric(as.character(Price)),
         Prev.Close = as.numeric(as.character(Prev.Close)),
         ATR = as.numeric(as.character(ATR)),
         Beta = as.numeric(as.character(Beta)),
         Perf.YTD = as.numeric(str_remove(Perf.YTD,"%"))/100,
         Perf.Year = as.numeric(str_remove(Perf.Year,"%"))/100,
         Perf.Half.Y = as.numeric(str_remove(Perf.Half.Y,"%"))/100,
         Perf.Quarter = as.numeric(str_remove(Perf.Quarter,"%"))/100,
         Perf.Month = as.numeric(str_remove(Perf.Month,"%"))/100,
         Perf.Week = as.numeric(str_remove(Perf.Week,"%"))/100,
         RSI..14. = as.numeric(as.character(RSI..14.)),
         EPS..ttm. = as.numeric(str_remove(EPS..ttm.,"%"))/100,
         EPS.next.Y = as.numeric(str_remove(EPS.next.Y,"%"))/100,
         EPS.next.Q = as.numeric(str_remove(EPS.next.Q,"%"))/100,
         EPS.this.Y = as.numeric(str_remove(EPS.this.Y,"%"))/100,
         EPS.next.Y.1 = as.numeric(str_remove(EPS.next.Y.1,"%"))/100,
         EPS.next.5Y = as.numeric(str_remove(EPS.next.5Y,"%"))/100,
         EPS.past.5Y = as.numeric(str_remove(EPS.past.5Y,"%"))/100,
         Sales.past.5Y = as.numeric(str_remove(Sales.past.5Y,"%"))/100,
         Sales.Q.Q = as.numeric(str_remove(Sales.Q.Q,"%"))/100,
         EPS.Q.Q = as.numeric(str_remove(EPS.Q.Q,"%"))/100,
         ROA = as.numeric(str_remove(ROA,"%"))/100,
         ROE = as.numeric(str_remove(ROE,"%"))/100,
         ROI = as.numeric(str_remove(ROI,"%"))/100,
         X52W.High = as.numeric(str_remove(X52W.High,"%"))/100,
         X52W.Low = as.numeric(str_remove(X52W.Low,"%"))/100,
         Target.Price = as.numeric(as.character(Target.Price)),
         Short.Ratio = as.numeric(as.character(Short.Ratio)),
         Short.Float = as.numeric(str_remove(Short.Float,"%"))/100,
         Payout = as.numeric(str_remove(Payout,"%"))/100,
         Gross.Margin = as.numeric(str_remove(Gross.Margin,"%"))/100,
         Inst.Trans = as.numeric(str_remove(Inst.Trans,"%"))/100,
         Inst.Own = as.numeric(str_remove(Inst.Own,"%"))/100,
         Insider.Trans = as.numeric(str_remove(Insider.Trans,"%"))/100,
         Insider.Own = as.numeric(str_remove(Insider.Own,"%"))/100,
         X52W.Low = as.numeric(str_remove(X52W.Low,"%"))/100,
         LT.Debt.Eq = as.numeric(as.character(LT.Debt.Eq)),
         Debt.Eq = as.numeric(as.character(Debt.Eq)),
         Current.Ratio = as.numeric(as.character(Current.Ratio)),
         Quick.Ratio = as.numeric(as.character(Quick.Ratio)),
         P.FCF = as.numeric(as.character(P.FCF)),
         P.C = as.numeric(as.character(P.C)),
         P.B = as.numeric(as.character(P.B)),
         P.S = as.numeric(as.character(P.S)),
         PEG = as.numeric(as.character(PEG)),
         Forward.P.E = as.numeric(as.character(Forward.P.E)),
         P.E = as.numeric(as.character(P.E)),
         Recom = as.numeric(as.character(Recom)),
         Employees = as.numeric(as.character(Employees)),
         Outlook.Growth = (Target.Price - Prev.Close)/Prev.Close,
         Volatility_Range = abs(as.numeric(str_remove(str_split_fixed(Volatility," ",2)[,2],"%")) - as.numeric(str_remove(str_split_fixed(Volatility," ",2)[,1],"%")))) %>%
  distinct() %>%
    rename("Volume" = Volume.x) %>%
  select(-c(SMA20,SMA50,Index,Income,Dividend..,Optionable,Shortable,
            Earnings,SMA200,Target.Price,X52W.High,X52W.Low,X52W.Range,
            Rel.Volume,Avg.Volume,Volume.y,ATR,Volatility,Prev.Close,
            Price,Change,Open,High,Low,Adjusted,Volume,Date)) %>%
  select(Stock,Close,Outlook.Growth,contains("Rank"),everything())

## Applying More Rigid Filters
Pool_Results_Potential_Buys = Pool_Results %>%
  filter(ROE > 0,
         ROA > 0,
         ROI > 0,
         Insider.Own > 0,
         Sales.Q.Q > 0,
         Sales.past.5Y > 0,
         EPS.this.Y >0,
         EPS.Q.Q > 0,
         EPS.next.Q > 0,
         EPS.past.5Y > 0,
         EPS.next.5Y > 0,
         EPS.next.Y.1 > 0,
         Profit.Margin > 0,
         Outlook.Growth > 0) %>%
  filter(Close_PD_50_Norm >= 0,
         Close_Slope_50_Norm >= 0,
         Close_High_PD_Norm >= -0.15,
         Close_PD_50_200_Norm >= 0,
         Close_Slope_200_Norm >=0) %>%
  filter(Pseudo_Beta_PD > 0)
Pool_Results_Interesting_Behavior = Pool_Results %>%
  mutate(Outlook.Growth_Rank = scales::rescale(Outlook.Growth,c(0,1))) %>%
  filter(Outlook.Growth_Rank >= quantile(Outlook.Growth_Rank,0.99,na.rm = T) |
           Volume_SD_Norm_Rank >= quantile(Volume_SD_Norm_Rank,0.99,na.rm = T) |
           Price_Range_15_SD_Norm_Rank <= quantile(Price_Range_15_SD_Norm_Rank,0.01,na.rm = T) |
           Pseudo_Beta_PD_Rank >= quantile(Pseudo_Beta_PD_Rank,0.99,na.rm = T)) %>%
  select(-Outlook.Growth_Rank)
Pool_Results_Potential_Buys = Pool_Results_Potential_Buys %>%
  bind_rows(Pool_Results_Interesting_Behavior)

## Reducing Historical Data to Reduced Selections
Tickers = unique(Pool_Results$Stock)
Total_Results = Combined_Results %>%
  filter(Stock %in% Tickers) %>%
  left_join(Market_Ind) %>%
  na.omit()

# Saving Pool Results and Reduced Raw Data
if(Local_S){
  save(Pool_Results,Total_Results,Pool_Results_Potential_Buys,
       file = paste0(Root_Folder,"/Data//Pool_Results.RDATA"))
}
if(Google_Drive_S){
    save(Pool_Results,Total_Results,Pool_Results_Potential_Buys,
         file = paste0(tempdir(),'/',"Pool_Results.RDATA"))
    Check = drive_find("Pool_Results.RDATA")
    if(nrow(Check) > 0){
      drive_rm("Pool_Results.RDATA")
    }
    drive_upload(media = paste0(tempdir(),'/',"Pool_Results.RDATA"),
                   path = "Pool_Results.RDATA")
}
```
## Daily Stock Update {.tabset .tabset-fade}
```{r Final Reports,echo = F}
if(Google_Drive_L){
  File = drive_download(file = "NASDAQ Historical.RDATA",
                        overwrite = T)
  load(File$local_path)
  rm(File)
  File = drive_download(file = "Market_Ind.RDATA",
                        overwrite = T)
  load(File$local_path)
  rm(File)
  File = drive_download(file = "Pool_Results.RDATA",
                        overwrite = T)
  load(File$local_path)
  rm(File)
}
if(Local_L){
  load(paste0(Root_Folder,"/Data/NASDAQ Historical.RDATA"))
  load(paste0(Root_Folder,"/Data//Market_Ind.RDATA"))
  load(paste0(Root_Folder,"/Data//Pool_Results.RDATA"))
}
```

### Current Market Status

```{r Market Status,echo = F}
## Segmenting Data
Plot_Date = max(Plot_DF$Date) %m-% months(6)
MIND_DF = Plot_DF %>%
  filter(Date >= Plot_Date)
Current_Status = Market_Ind %>%
  arrange(desc(Date)) %>%
  head(1)

## Plot Examining Market Direction Designation
p1 = ggplot(MIND_DF,aes(x = Date,y = Adjusted,color = Market_Status)) +
  geom_point() +
  labs(x = "Date",
       y = "Adjusted",
       title = "Market Status of Past 6 Months",
       subtitle = paste0("Current status = ",Current_Status$Market_Status," :: Date = ",Current_Status$Date),
       color = "Market Status") +
  facet_wrap(Stock~.,nrow = 3,ncol = 1,scales = "free_y")
print(p1)
```

### Stock Monitoring Table (Unfiltered)

```{r Table,echo = F}
## Interactive Table of Stock Selections
DT::datatable(data = Pool_Results,
              filter = list(position = 'top'))
```

### Stock Monitoring Table (Filtered to Buy Positions)

```{r Table PBs,echo = F}
## Interactive Table of Stock Selections
DT::datatable(data = Pool_Results_Potential_Buys,
              filter = list(position = 'top'))
```

### Stock Monitoring Charts

```{r Charts,echo = F}
## Plotting last 6 Months of Stock Data
Tickers = unique(Pool_Results_Potential_Buys$Stock)
for(i in 1:length(Tickers)){
  TMP = Combined_Results %>%
    filter(Stock == Tickers[i])
  x = as.xts(OHLCV(TMP),order.by = TMP$Date)
  x = last(x,'6 months')
  chartSeries(x,name = Tickers[i])
  rm(x,TMP)
}
```
##
