---
title: "Total Market Analysis"
author: "Emerson COMRES"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: cerulean
editor_options: 
  chunk_output_type: console
---

    If this is the first RMD made in the project, you will need to make a setup script in the Project_Folder root directory.

```{r setup, include=FALSE}
## Loading COMRES Data Science Package
library(EmersonDataScience)

Project_Folder = rprojroot::find_rstudio_root_file()

load_or_install(c("tidyverse","lubridate","TTR","rpart","rpart.plot"))

```

```{r}
Stocks_DF = read.csv(str_c(Project_Folder,"/Data/Historical_Data_Stocks.csv"))

Stock_Summary = Stocks_DF %>%
  rename("DateTime" = X) %>%
  mutate(DateTime = ymd_hms(DateTime))

Stock_TI = Stock_Summary %>%
  group_by(stock) %>%
  mutate(RSI = TTR::RSI(close),
         MACD = MACD(close)[,1] - MACD(close)[,2],
         Week_Return = (close - lag(close,5))/lag(close,5)) %>%
  na.omit()

Market_TI = Stock_Summary %>%
  group_by(DateTime) %>%
  select_if(is.numeric) %>%
  summarise_all(mean) %>%
  mutate(RSI = TTR::RSI(close),
         MACD = MACD(close)[,1] - MACD(close)[,2]) %>%
  na.omit() %>%
  select(DateTime,
         "M_RSI" = RSI,
         "M_MACD" = MACD) 

Total_TI = Stock_TI %>%
  left_join(Market_TI)

fit = rpart(Week_Return ~ RSI,
            data = Total_TI,
            method = "anova",model = F,x = F, y = F,
            control = rpart.control(
              max_depth = 5,
              minsplit = round(nrow(Total_TI)*0.05)))

rpart.plot(fit)
```



```{r}
Stocks_DF = read.csv(str_c(Project_Folder,"/Data/Historical_Data_Stocks.csv"))

Market_Summary = Market_DF %>%
  mutate(Open_Ratio = (open-low)/(high-low),
         Close_Ratio = (close-low)/(high-low))

Stats = list()
for(i in 0:4){
  for(col in c("Open_Ratio","Close_Ratio")){
    OR = Market_Summary[,col][Market_Summary$Market_Day == i]
    MED = median(OR)
    LSD = MED - 2*1.4826*mad(OR[OR<MED])
    USD = MED + 2*1.4826*mad(OR[OR>=MED])
    Stats[[str_c(i,"-",col)]] = data.frame(
      Day = i,
      Col = col,
      Center = MED,
      UL = USD,
      LL = LSD
    )
  }
}

Stats = plyr::ldply(Stats,data.frame)

## Looking at Typical Day Patterns
ggplot(Stats,aes(x = Day,y = Center,color = Col)) +
  geom_errorbar(aes(y = Center,ymin = LL,ymax = UL),
                position = "dodge") +
  geom_point() +
  coord_flip() +
  scale_y_continuous(limits = c(0,1),labels = percent) +
  labs(title = "Open / Close Ratio To Average Day High",
      subtitle = "(Two Sided 2*MAD*1.4826) : Normality Assumption ~ STDEV",
       y = "(Value - Low)/(High - Low)",
       color = "")
```

